In [1]:
import numpy as np


In [2]:
np.random.seed(0) # seed for reproducibility

x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(3, 4)) # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5)) # Three-dimensional array

In [3]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [4]:
print("dtype:", x3.dtype)

dtype: int64


In [5]:
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes")

itemsize: 8 bytes
nbytes: 480 bytes


In [6]:
x1

array([5, 0, 3, 3, 7, 9])

In [7]:
x1[0
  ]

5

In [8]:
x1[4]

7

In [9]:
x1[-1]

9

In [10]:
x1[-2]

7

In [11]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [12]:
x2[0, 0]

3

In [13]:
x2[2, 0]

1

In [14]:
x2[2, -1]

7

In [16]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [19]:
x1[0] = 3.14159 # this will be truncated
x1

array([3, 0, 3, 3, 7, 9])

In [21]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
x[:5] # the first five elements

array([0, 1, 2, 3, 4])

In [23]:
x[5:] # elements after index 5

array([5, 6, 7, 8, 9])

In [24]:
x[4:7] # middle sub-array

array([4, 5, 6])

In [25]:
x[::2] # every other element

array([0, 2, 4, 6, 8])

In [26]:
x[1::2] # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [27]:
x[::-1] # elements, reversed

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [30]:
x[5::-2] # reversed every other from index 5

array([5, 3, 1])