In [1]:
import numpy as np

In [2]:
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [3]:
np.array([3.14, 3, 2, 3])

array([3.14, 3.  , 2.  , 3.  ])

In [4]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [5]:
# nested lists result in multi-dimensional array
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [6]:
# Create a length-10 integer array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [9]:
# Create an array filled with a linear sequence
# starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)



array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
# Create a 3x3 array of uniformly distrbuted
# random values between 0 and 1
np.random.random((3,3))

array([[0.6803279 , 0.67411379, 0.83845232],
       [0.63711931, 0.79644539, 0.2996543 ],
       [0.19586737, 0.50093604, 0.2175344 ]])

In [14]:
# Create a 3x3 array of normally distributed random values 
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.47962358, -0.64676043, -1.42137708],
       [-0.70924264, -0.76719795, -0.68231231],
       [ 0.19238878,  0.14999005,  0.08806775]])

In [15]:
np.random.randint(0, 10, (3, 3))

array([[4, 3, 7],
       [9, 3, 8],
       [4, 8, 3]])

In [17]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [28]:
np.ones(10, dtype=np.int16)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)